# CSC3095:Web Platform for Digital Deployment of Virtual Servers
BSc Computer Science
by Plamen Kolev
Project Supervisor: Dr. Neil Speirs

## Abstract














----
GUTTER
----

// # CSC3095:Project and Dissertation in Computing Science
// Plamen Kolev

## Virtualbox networking

Considerations:
Create and assign a NAT(network address translation) to each virtual machine where host 127.0.0.1:22 to 10.0.0x:22 is port-forwarded for management purposes.

Useful commands:

`vboxmanage list natnets` : lists all NAT networks and shows port forward rules

`vboxmanage list dhcpservers`

Initially the NAT did not provide outside access to the testing virtual machine

Simpler setting is to use a bridged adapter for the guest, install virtualbox-guest-dkms virtualbox-guest-utils allows the host to query the instance.
For example, if the machine's name is `server_1`, running  `vboxmanage guestproperty enumerate server_1` from the host yields very useful information.

[[app-listing]]
[source,shell]

----
vboxmanage guestproperty enumerate server_1 | grep  V4/IP | egrep -oh  "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}.[0-9]{1,3}"
----

The command will grab only the IP of the guest.

As the guest operating system, i am using ubuntu 16.04 and deploy it with a vagrant file shown below.
[[app-listing]]
[source,shell]

----
Vagrant.configure(2) do |config|
    config.vm.provider "virtualbox" do |vb|
    # very important, otherwise the vm will try to raise the
    # cable connection that does not exist
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end
end
----

I was having issues making the chef server weui accessible from the outside
I have issue with ssl as the originator is port-forwarded : solution, make the network private instead of public

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-chef-12-configuration-management-system-on-ubuntu-14-04-servers < used this guide for some of the initial chef setup

# creating certificate pem file
http://www.beginninglinux.com/home/server-administration/openssh-keys-certificates-authentication-pem-pub-crt
