        Vagrant.configure(2) do |config|
          config.ssh.insert_key = false
          config.vm.box = "plamen-kolev/centos"
          config.vm.network "private_network", ip: "88.168.56.253", :bridge => 'vboxnet0'
          config.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
            vb.name = "Centos Base"
            vb.memory = "1024"
          end
        end
