source 'https://rubygems.org'

gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'commander', '~> 4.4', '>= 4.4.3'
gem 'random-word', '~> 1.3'
gem 'dotenv', '~> 2.2'
gem 'activerecord', '~> 5.0', '>= 5.0.1'
gem 'slugify', '~> 1.0', '>= 1.0.6'
gem 'vagrant-vbguest', '~> 0.13.0'

group :development, :test do
  gem 'sqlite3', '~> 1.3', '>= 1.3.13'
end