source 'https://rubygems.org'

gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'commander', '~> 4.4', '>= 4.4.3'
gem 'random-word', '~> 1.3'
gem 'activerecord', '~> 5.0', '>= 5.0.1'
gem 'slugify', '~> 1.0', '>= 1.0.6'
gem 'vagrant-vbguest', '~> 0.13.0'
gem 'figaro', '~> 1.1', '>= 1.1.1'
gem "deeploy", :path => "deeploy"
gem 'simple_form', '~> 3.4'

group :production do
  gem 'mysql2', '~> 0.4.5'
end

group :development, :test do
  gem 'sqlite3', '~> 1.3', '>= 1.3.13'
  gem 'byebug', '~> 9.0', '>= 9.0.6'
end
